import { Fira_Code } from "next/font/google";
import Header from './components/Header';
import "./globals.css";

const FiraCode = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={FiraCode.className}>
				<Header />
				{children}
			</body>
    </html>
  );
}
